console.log("✅ Page loaded: script.js is running");

// ── Element refs ──
const themeBtn   = document.getElementById("themeBtn");
const countBtn   = document.getElementById("countBtn");
const countLabel = document.getElementById("countLabel");
const lastUpdated = document.getElementById("lastUpdated");

// ── State ──
let isDark     = false;
let clickCount = 0;

// ── 1. Theme Toggle + localStorage persistence ──

/**
 * Apply a theme by adding/removing the 'dark' class on <body>
 * and saving the choice to localStorage.
 * @param {boolean} dark - true for dark mode
 */
function applyTheme(dark) {
  isDark = dark;
  if (isDark) {
    document.body.classList.add("dark");
  } else {
    document.body.classList.remove("dark");
  }
  // Persist to localStorage
  localStorage.setItem("portfolio_theme", isDark ? "dark" : "light");
  console.log("🌙 Theme applied. isDark =", isDark);
}

// On page load: read saved theme from localStorage
const savedTheme = localStorage.getItem("portfolio_theme");
if (savedTheme === "dark") {
  applyTheme(true);
  console.log("💾 Loaded saved theme: dark");
} else {
  applyTheme(false);
  console.log("💾 Loaded saved theme: light");
}

// Theme button click handler
if (themeBtn) {
  themeBtn.addEventListener("click", () => {
    console.log("🎛️ Theme button clicked");
    applyTheme(!isDark);
  });
} else {
  console.log("❌ ERROR: themeBtn not found. Check id='themeBtn' in index.html");
}

// ── 2. Click counter ──

function increaseCount() {
  clickCount = clickCount + 1;
  console.log("🖱️ Hi button clicked. clickCount =", clickCount);
  if (countLabel) countLabel.textContent = clickCount;
}

if (countBtn) {
  countBtn.addEventListener("click", () => {
    console.log("➕ Count button clicked");
    increaseCount();
  });
} else {
  console.log("❌ ERROR: countBtn not found. Check id='countBtn' in index.html");
}

// ── 3. Last Updated (auto-generated by JS) ──
if (lastUpdated) {
  const today = new Date();
  const year  = today.getFullYear();
  const month = String(today.getMonth() + 1).padStart(2, "0");
  const day   = String(today.getDate()).padStart(2, "0");
  const dateStr = `${year}-${month}-${day}`;
  lastUpdated.textContent = `Last updated: ${dateStr}`;
  console.log("📅 Last updated set to:", dateStr);
}
